#!/usr/bin/env python3
#-*- coding: utf-8 -*-

from argparse  import ArgumentParser
from common.logger import Logger
from beacons.global_sync import ServerGS

    

def server(args):
    log = Logger(Logger.WRITE, file_name="/home/pi/logs/server.log")
    srv = ServerGS(log)
    srv.run()



parser = ArgumentParser()
subparsers = parser.add_subparsers()


server_parser = subparsers.add_parser('server')
server_parser.set_defaults(func=server)


args = parser.parse_args()
args.func(args)


