#!/usr/bin/env python3
#-*- coding: utf-8 -*-

from argparse  import ArgumentParser

from beacons.server import Server

    

def server(args):

    srv = Server()
    srv.run()



parser = ArgumentParser()
subparsers = parser.add_subparsers()


server_parser = subparsers.add_parser('server')
server_parser.set_defaults(func=server)


args = parser.parse_args()
args.func(args)


