BOARD = esp32
CHIP = esp32

#Arduino file
SKETCH = pthread.ino

COMMON = ../common
#Setup all libs used !
LIBS =  $(ESP_LIBS)/EEPROM \


# Congratulations! You made a pretty Makefile :)
# Now let the grown-ups do the hard work :D
MODULEMK_DIR = ..
include $(MODULEMK_DIR)/Module.mk

