#ifndef KALMAN_CONSTANTS_H
#define KALMAN_CONSTANTS_H

#define INPUT_DATA_NUMBER 4
#define SYSTEM_STATE_NUMBER 8


//Noise from Sensors
#define BEACONS_NOISE_X 1600
#define BEACONS_NOISE_Y 400
#define ACC_NOISE  10000

//ERROR from our model
#define ESTIMATION_ERROR_X  150
#define ESTIMATION_ERROR_Y  150

#define ESTIMATION_ERROR_BIAS_X 300
#define ESTIMATION_ERROR_BIAS_Y 300

#define ESTIMATION_ERROR_VX     10
#define ESTIMATION_ERROR_VY     10

#define ESTIMATION_ERROR_ACCX   0
#define ESTIMATION_ERROR_ACCY   0

//INIT VALUE FOR MODEL PREDICTION
#define INIT_VALUE 1000


#endif